### ISSUE TITLE
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('<URL>') does not match the recipient window's origin ('<URL>').

### ISSUE THREAD

**Issue by Genotronwastaken** [FrancoisMentec/PoE-Trade-Extension#1]
I disabled uBlockorigin, UBlockoriginplus and uMatrix for this log. (so its not those)
[www.pathofexile.com-1577560588086.log](https://github.com/FrancoisMentec/PoE-Trade-Extension/files/4007365/www.pathofexile.com-1577560588086.log)

**Comment by dakota-bacoch** [comment]
I had this same problem, I made the mistake of sharing it the wrong way from pob.party. In the instruction it says in bold the correct way to share it. Your code that you paste into the extension should not be a pob code but a pob.party url.

**Comment by Genotronwastaken** [comment]
Okay heres the thing. I copied the correct code from pob.party clicked the big blue "set bob" the whole thing flashed and then i read below build code set. I didn't catch the field above as an empty field an thought the extension grabbed it from the clipboard. aka the above errors are generated because there was no pob.party code set.

I'll leave the issue open because ideally the extension shouldn't generate any errors while no build is inserted. (So you can look up things normally without uninstalling)

**Comment by FrancoisMentec** [comment]
c534177c71bee078855369fd6f7e44aa394f8fee Now you should get a more appropriate error message when the pob.party sharing link is incorrect (like an empty string in your case).
