### ISSUE TITLE
cant seem to find the set pob button

### ISSUE THREAD

**Issue by Smeagol001** [FrancoisMentec/PoE-Trade-Extension#2]
hello
seems i cant find the set pob button you describe.
shopuld it be on the pob.party or on pathofexile/trade
if it schould be on trade i only see the "show" button and there only is a show hide disabe button but no set pob button so wher can ii find it since on pob.party i cant seem to see any added buttons at all

**Comment by jarekb84** [comment]
It'll show up as an icon at the top right of the chrome toolbar, not in the trade site itself.

![image](https://user-images.githubusercontent.com/667983/71551498-b53ddc80-29ae-11ea-9e79-91e0e1fb4f34.png)

**Comment by FrancoisMentec** [comment]
8c1c3eb7ce768fbcdc2b31ef5d0c33549316081a I added an image of the popup to the README.
