### ISSUE TITLE
Uncaught error

### ISSUE THREAD

**Issue by dakota-bacoch** [FrancoisMentec/PoE-Trade-Extension#5]
Uncaught (in promise) ReferenceError: load_textures is not defined
    at Object.active (VM17:53)
    at L (webfont.js:21)
    at oa (webfont.js:24)
    at W.g (webfont.js:23)
    at webfont.js:21

**Comment by FrancoisMentec** [comment]
This error is on the side of pob.party, not much I can do without more details. Do pob.party works correctly when opened in a different tab? When the extension is disabled? What exactly happens? Does it completely prevent the extension from working? Does it happen all the time?

**Comment by FrancoisMentec** [comment]
Don't hesitate to re-open if you have further details, I'm closing it for now.
