### ISSUE TITLE
string import

### ISSUE THREAD

**Issue by Smeagol001** [FrancoisMentec/PoE-Trade-Extension#6]
could you maybe make it so that we just put the pob string into your extension and it does all the work?

**Comment by FrancoisMentec** [comment]
It was my intention at first, but I can only communicate with pob.party through user events, and pasting text in the field dedicated to pob code doesn't work correctly. I can paste text only with chrome, but not with firefox nor custom made events.

In a future version, I'll try to remove pob.party and compile pob to webassembly myself, or use a transpiler from lua to javascript. It should solve a lot of issues (including this one) and make it faster to use, but I don't have the time to do this right now.

**Comment by Smeagol001** [comment]
okay just thought of asking :)
its good work  i must say

only thing that isnt cool is that you cant autoinstall/update the addon since its not on chrome store any plans to add that?

**Comment by FrancoisMentec** [comment]
https://github.com/FrancoisMentec/PoE-Trade-Extension#from-the-store
Chrome refuses to add it to their store for whatever reason, but it's available on firefox.
